#!/usr/bin/env php
<?php

$basePath = dirname(__DIR__);

require $basePath . '/vendor/autoload.php';

$app = require_once $basePath . '/bootstrap/app.php';

exit(
    $app->make(\Illuminate\Console\Kernel::class)->handle(
        $input = new \Symfony\Component\Console\Input\ArgvInput,
        new \Symfony\Component\Console\Output\ConsoleOutput
    )
);
